import { Board } from '@/types';

export const dummyBoard: Board = {
  title: 'Product Launch Q3',
  columns: [
    {
      id: 'column-1',
      title: 'To Do',
      color: '#888888',
      cards: [
        {
          id: 'card-1',
          title: 'Design homepage mockup',
          details: 'Create high-fidelity mockups for the landing page with responsive variants.',
          priority: 'high',
          dueDate: '2026-07-10',
          tags: [{ label: 'design', color: '#753991' }],
          assignee: { name: 'Alice Chen', avatar: 'AC' },
          commentCount: 3,
        },
        {
          id: 'card-2',
          title: 'Set up database schema',
          details: 'Design and implement PostgreSQL database structure for users and projects.',
          priority: 'urgent',
          dueDate: '2026-06-25',
          tags: [{ label: 'backend', color: '#209dd7' }, { label: 'db', color: '#032147' }],
          assignee: { name: 'Bob Torres', avatar: 'BT' },
          commentCount: 5,
        },
        {
          id: 'card-3',
          title: 'API documentation',
          details: 'Write comprehensive API documentation with examples and error codes.',
          priority: 'medium',
          dueDate: null,
          tags: [{ label: 'docs', color: '#ecad0a' }],
          assignee: null,
          commentCount: 1,
        },
      ],
    },
    {
      id: 'column-2',
      title: 'In Progress',
      color: '#209dd7',
      cards: [
        {
          id: 'card-4',
          title: 'Implement authentication',
          details: 'Set up JWT-based authentication system with refresh tokens.',
          priority: 'high',
          dueDate: '2026-06-28',
          tags: [{ label: 'security', color: '#032147' }, { label: 'backend', color: '#209dd7' }],
          assignee: { name: 'Bob Torres', avatar: 'BT' },
          commentCount: 8,
        },
        {
          id: 'card-5',
          title: 'Build user dashboard',
          details: 'Create responsive dashboard UI with activity feed and stats widgets.',
          priority: 'medium',
          dueDate: '2026-07-05',
          tags: [{ label: 'frontend', color: '#753991' }],
          assignee: { name: 'Alice Chen', avatar: 'AC' },
          commentCount: 2,
        },
        {
          id: 'card-6',
          title: 'Notification system',
          details: 'Implement real-time notifications via WebSockets with in-app and email delivery.',
          priority: 'low',
          dueDate: '2026-07-15',
          tags: [{ label: 'backend', color: '#209dd7' }, { label: 'realtime', color: '#ecad0a' }],
          assignee: { name: 'Carol Wu', avatar: 'CW' },
          commentCount: 4,
        },
      ],
    },
    {
      id: 'column-3',
      title: 'Review',
      color: '#ecad0a',
      cards: [
        {
          id: 'card-7',
          title: 'Code review: Payment flow',
          details: 'Review and approve payment processing implementation with Stripe integration.',
          priority: 'urgent',
          dueDate: '2026-06-24',
          tags: [{ label: 'payments', color: '#209dd7' }, { label: 'security', color: '#032147' }],
          assignee: { name: 'Diana Park', avatar: 'DP' },
          commentCount: 12,
        },
        {
          id: 'card-8',
          title: 'UI review: Mobile responsiveness',
          details: 'Test and verify responsive design on all devices and screen sizes.',
          priority: 'medium',
          dueDate: '2026-06-30',
          tags: [{ label: 'design', color: '#753991' }, { label: 'mobile', color: '#ecad0a' }],
          assignee: { name: 'Alice Chen', avatar: 'AC' },
          commentCount: 6,
        },
        {
          id: 'card-9',
          title: 'Security audit',
          details: 'Conduct security review of authentication, API endpoints, and data handling.',
          priority: 'high',
          dueDate: '2026-06-27',
          tags: [{ label: 'security', color: '#032147' }],
          assignee: { name: 'Diana Park', avatar: 'DP' },
          commentCount: 3,
        },
      ],
    },
    {
      id: 'column-4',
      title: 'Testing',
      color: '#753991',
      cards: [
        {
          id: 'card-10',
          title: 'Unit tests for utils',
          details: 'Write comprehensive unit tests for all utility functions with edge cases.',
          priority: 'medium',
          dueDate: '2026-07-02',
          tags: [{ label: 'testing', color: '#209dd7' }],
          assignee: { name: 'Carol Wu', avatar: 'CW' },
          commentCount: 1,
        },
        {
          id: 'card-11',
          title: 'E2E tests: User flow',
          details: 'Test complete user journey from signup to checkout with Playwright.',
          priority: 'high',
          dueDate: '2026-07-08',
          tags: [{ label: 'testing', color: '#209dd7' }, { label: 'e2e', color: '#753991' }],
          assignee: { name: 'Carol Wu', avatar: 'CW' },
          commentCount: 2,
        },
      ],
    },
    {
      id: 'column-5',
      title: 'Done',
      color: '#032147',
      cards: [
        {
          id: 'card-12',
          title: 'Project setup',
          details: 'Initialize Next.js project with TypeScript, ESLint, and testing infrastructure.',
          priority: 'none',
          dueDate: '2026-06-15',
          tags: [{ label: 'infra', color: '#032147' }],
          assignee: null,
          commentCount: 0,
        },
        {
          id: 'card-13',
          title: 'Environment configuration',
          details: 'Configure dev, staging, and production environments with CI/CD pipelines.',
          priority: 'none',
          dueDate: '2026-06-16',
          tags: [{ label: 'devops', color: '#209dd7' }],
          assignee: { name: 'Bob Torres', avatar: 'BT' },
          commentCount: 0,
        },
        {
          id: 'card-14',
          title: 'Git workflow setup',
          details: 'Set up branching strategy and repository structure with protected branches.',
          priority: 'none',
          dueDate: null,
          tags: [],
          assignee: null,
          commentCount: 0,
        },
      ],
    },
  ],
};
